---
title: "stat443_madrid_outOfSampleRMSE"
author: "chloe"
date: "March 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## splitting train/ holdout set 
```{r}
hold.month<-monthly.means[c(193:nrow(monthly.means)-1),] # full 2017 months
dim(hold.month) # 12 5
train.month<-monthly.means[c(1:192),]
dim(train.month) # 192 5
```


## Additional out-of-sample RMSE code 
*RUN AFTER MAIN SCRIPT FILE
###Persistence
```{r}
## monthly.means contains all data
## hold.month 13 5
## train.month 191 5
nt<-nrow(train.month)
nh<-nrow(hold.month)
mse<-0
fc<-train.month[nt,2] # CO
zt<-hold.month[1,2]
fcerror<-zt-fc
mse<-mse+fcerror^2
for (i in 2:nh){
  fc<-hold.month[i-1,2]
  zt<-hold.month[i,2]
  fcerror<-zt-fc
  mse<-mse+fcerror^2
}
rmse<-sqrt(mse/nh)
rmse # 0.07515032
```
###Average
```{r}
cumsum<-sum(train.month[,2])
mse<-0
fc<-cumsum/nt
zt<-hold.month[1,2]
fcerror<-zt-fc
mse<-mse+fcerror^2
for (i in 2:nh){
  cumsum<-cumsum+hold.month[i-1,2]
  fc<-cumsum/(nt+i-1)
  zt<-hold.month[i,2]
  fcerror<-zt-fc
  mse<-mse+fcerror^2
}
rmse<-sqrt(mse/nh)
rmse #0.1792378
```
###Additive Holt Winters
```{r}
hw.co <- HoltWinters(tsCO,seasonal='additive')
print(sqrt(hw.co$SSE/(nrow(train.month)-12))) # in sample rmse = 0.08480218

## train.month 
## hold.month
### out-of-sample
nt<-nrow(train.month)
nh<-nrow(hold.month)

alpha<-hw.co$alpha
beta<-hw.co$beta
gamma<-hw.co$gamma
lev<-hw.co$coefficients[1]
tre<-hw.co$coefficients[2]
s1<-hw.co$coefficients[3]
s2<-hw.co$coefficients[4]
s3<-hw.co$coefficients[5]
s4<-hw.co$coefficients[6]
s5<-hw.co$coefficients[7]
s6<-hw.co$coefficients[8]
s7<-hw.co$coefficients[9]
s8<-hw.co$coefficients[10]
s9<-hw.co$coefficients[11]
s10<-hw.co$coefficients[12]
s11<-hw.co$coefficients[13]
s12<-hw.co$coefficients[14]

sse<-0
fc<-lev+tre+s1
zt<-hold.month[1,2]
newfc<-fc
rm(fcvec)
fcvec<-vector()
fcvec[1]<-fc
fcerror<-zt-fc
sse<-sse+fcerror^2
vprev<-lev
bprev<-tre
for(i in 2:nh){
  # d = 12
  d=12
  if ((i-1)%%d==0 ){s=s12}
  if ((i-1)%%d==1 ){s=s1}
  if ((i-1)%%d==2 ){s=s2}
  if ((i-1)%%d==3 ){s=s3}
  if ((i-1)%%d==4 ){s=s4}
  if ((i-1)%%d==5 ){s=s5}
  if ((i-1)%%d==6 ){s=s6}
  if ((i-1)%%d==7 ){s=s7}
  if ((i-1)%%d==8 ){s=s8}
  if ((i-1)%%d==9 ){s=s9}
  if ((i-1)%%d==10 ){s=s10}
  if ((i-1)%%d==11 ){s=s11}
  if ((i-1)%%d==12 ){s=s12}
  
  if (i%%d==0 ){sn=s11}
  if (i%%d==1 ){sn=s1}
  if (i%%d==2 ){sn=s2}
  if (i%%d==3 ){sn=s3}
  if (i%%d==4 ){sn=s4}
  if (i%%d==5 ){sn=s5}
  if (i%%d==6 ){sn=s6}
  if (i%%d==7 ){sn=s7}
  if (i%%d==8 ){sn=s8}
  if (i%%d==9 ){sn=s9}
  if (i%%d==10 ){sn=s10}
  if (i%%d==11 ){sn=s11}
  if (i%%d==12 ){sn=s12}
  
  vnew<-alpha*(hold.month[i-1,2]-s)+(1-alpha)*(vprev+bprev)
  bnew<-beta*(vnew-vprev)+(1-beta)*bprev
  snew<-gamma*(hold.month[i-1,2]-vnew)+(1-gamma)*s
  fc<-vnew+bnew+sn
  fcvec[i]<-fc
  zt<-hold.month[i,2]
  fcerror<-zt-fc
  sse<-sse+fcerror^2
  vprev<-vnew
  bprev<-bnew
  if ((i-1)%%d==0 ){s12<-snew}
  if ((i-1)%%d==1 ){s1<-snew}
  if ((i-1)%%d==2 ){s2<-snew}
  if ((i-1)%%d==3 ){s3<-snew}
  if ((i-1)%%d==4 ){s4<-snew}
  if ((i-1)%%d==5 ){s5<-snew}
  if ((i-1)%%d==6 ){s6<-snew}
  if ((i-1)%%d==7 ){s7<-snew}
  if ((i-1)%%d==8 ){s8<-snew}
  if ((i-1)%%d==9 ){s9<-snew}
  if ((i-1)%%d==10 ){s10<-snew}
  if ((i-1)%%d==11 ){s11<-snew}
  if ((i-1)%%d==12 ){s12<-snew}
}
rmse=sqrt(sse/nh)
rmse # 0.07493605
```
### AR2
```{r}
ar2=arima(ts(train.month[,2]),order=c(2,0,0),method = 'CSS')
sqrt(ar2$sigma2) #in-sample:  0.1020539
nt<-nrow(train.month)
nh<-nrow(hold.month)
phivec<-as.vector(c(ar2$coef[1],ar2$coef[2]))
miu<-ar2$coef[3]
y<-c(train.month[nrow(train.month)-1,2],train.month[nrow(train.month),2],hold.month[,2])
length(y) # 15
y<-y-miu
rm(fcvec)
fcvec<-vector()
sse<-0
for (i in 1:nh){
  u<-c(y[i+1],y[i])
  fc<-miu+phivec%*% as.vector(u)
  fcvec[i]<-fc
  zt<-hold.month[i,2]
  fcerror<-zt-fc
  sse<-sse+fcerror^2
}
rmse=sqrt(sse/nh)
rmse #0.07014425
fcvec 
```
### AR3
```{r}
ar3=arima(ts(train.month[,2]),order=c(3,0,0),method = 'CSS')
sqrt(ar3$sigma2) #in-sample:0.09982481
nt<-nrow(train.month)
nh<-nrow(hold.month)
phivec<-as.vector(c(ar3$coef[1],ar3$coef[2],ar3$coef[3]))
miu<-ar3$coef[4]
y<-c(train.month[nrow(train.month)-2,2],train.month[nrow(train.month)-1,2],train.month[nrow(train.month),2],hold.month[,2])
length(y) # 16
y<-y-miu
rm(fcvec)
fcvec<-vector()
sse<-0
for (i in 1:nh){
  u<-c(y[i+2],y[i+1],y[i])
  fc<-miu+phivec%*% as.vector(u)
  fcvec[i]<-fc
  zt<-hold.month[i,2]
  fcerror<-zt-fc
  sse<-sse+fcerror^2
}
rmse=sqrt(sse/nh)
rmse #0.06768955
fcvec 
```
### AR1
```{r}
ar1=arima(ts(train.month[,2]),order=c(1,0,0),method = 'CSS')
sqrt(ar1$sigma2) #in-sample: 0.1141178
nt<-nrow(train.month)
nh<-nrow(hold.month)
phivec<-ar1$coef[1]
miu<-ar1$coef[2]
y<-c(train.month[nrow(train.month),2],hold.month[,2])
length(y) # 14
y<-y-miu
rm(fcvec)
fcvec<-vector()
sse<-0
for (i in 1:nh){
  u<-y[i]
  fc<-miu+phivec%*% as.vector(u)
  fcvec[i]<-fc
  zt<-hold.month[i,2]
  fcerror<-zt-fc
  sse<-sse+fcerror^2
}
rmse=sqrt(sse/nh)
rmse # 0.07355902
fcvec 
```
### ARMAX(2,0,0)+SO2+NO2 in/out of sample 
```{r}
armax=arima(ts(train.month[,2]),order=c(2,0,0), xreg=monthly.means[1:nrow(train.month),c(3,5)])
#armax
sqrt(armax$sigma2) # in-sample: 0.06870842
# out
train<-train.month[,c(2,3,5)]
hold<-hold.month[,c(2,3,5)]
phivec<-armax$coef[c(1,2)]
betas<-armax$coef[c(3,4,5)]
y<-rbind(train[nrow(train)-1,],train[nrow(train),],hold)
r<-vector()
for (j in 1:nrow(y)){
  r[j]<-y$CO[j]-c(1,y$NO2[j],y$SO2[j]) %*%betas
}
rm(fcvec)
fcvec<-vector()
sse<-0
for (i in 1:nh){
  fc<- t(c(1,y$NO2[i],y$SO2[i])) %*%betas + t(phivec)%*%c(r[i+1],r[i])
  fcvec[i]<-fc
  zt<-hold[i,1]
  fcerror<-zt-fc
  sse<-sse+fcerror^2
}
rmse=sqrt(sse/nh)
rmse # 0.1220484
fcvec 
```

### ARMA(2,0,0)(0,1,0)12 seasonal difference
```{r}
arima.season=arima(ts(train.month[,2]),order=c(2,0,0),seasonal=list(order=c(0,1,0),period=12))
sqrt(arima.season$sigma2) # 0.09475901
# out
phivec<-arima.season$coef[c(1,2)]
s<-12
y<-c(train.month[c((nrow(train.month)-13):nrow(train.month)),2],hold.month[,2])
length(y) # p+s+nh =2+12+12=26
rm(fcvec)
fcvec<-vector()
sse<-0
for (i in 1:nh){
  u<-c(y[i+13],y[1+12])-c(y[i+1],y[i])
  fc<- y[i+2]+ phivec %*%u
  fcvec[i]<-fc
  zt<-hold.month[i,2]
  fcerror<-zt-fc
  sse<-sse+fcerror^2
}
rmse=sqrt(sse/nh)
rmse #0.05346595
fcvec
```

